#Para recrear el entorno virtual: conda env create --file environment.yml

name: manejo_rutas_archivos
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - ipykernel
  - scikit-learn
  - pandas

